on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build

    
