on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
    
name: "source-code-analysis"
jobs:
  sourceCodeAnalysis:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        ref: ${{ github.ref_name }}

    - name: Set Sonar Branch
      if: ${{ github.ref_name != 'main'&& github.ref_name != 'master' }}
      run: echo "SONAR_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
        
    - name: scan
      uses: sonarsource/sonarcloud-github-action@v2.0.2
      with:
        args: >
          -Dsonar.sources=.
          -Dsonar.branch.name=${{ env.SONAR_BRANCH }}
