on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
    
name: "source-code-analysis"
jobs:
  sourceCodeAnalysis:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: scan
      uses: sonarsource/sonarcloud-github-action@v2.0.2
      with:
        args: >
          -Dsonar.sources=.
