on:
  workflow_call:
    secrets:
      PAT:
        required: true

name: "run-sh"
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with: 
          repository: Drastyn/actions
          ref: refs/heads/test-file-action-call
          token: ${{ secrets.PAT }}


      - name: run-sh
        run: |
          pwd
          ls
          chmod +x $HOME/actions/helpers/test.sh
          .$HOME/actions/helpers/test.sh
        shell: bash
