on:
  workflow_call:

name: "run-sh"
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: run-sh
        run: |
          chmod +x /helpers/test.sh
          ./helpers/test.sh
        shell: bash
